Controllers/CustomersController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TireWay.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
namespace TireWay.Controllers;

public class CustomersController : Controller
{
    private MyContext db;
    public CustomersController(MyContext context)
    {
        db = context;
    }
    [HttpGet("/customers")]
    public IActionResult Index()
    {
        return View("Index");
    }
    [HttpPost("/customers/register")]
    public IActionResult Register(Customer newCustomer)
    {    
        //Check if model state is valid
        if(!ModelState.IsValid){
            return Index();
        }
        //Check to see if Customer already exist in db
        if(db.Customers.Any(Customer => Customer.Phone == newCustomer.Phone)){
                ModelState.AddModelError("Phone", "already exists");
        }
        // Clear Any Previous customers when switching to a new one, no logout
        HttpContext.Session.Clear();
        //Add Customer to db 
        db.Customers.Add(newCustomer);
        db.SaveChanges();

        Invoice newInvoice = new Invoice()
        {
            CustomerId = newCustomer.CustomerId
        };
        db.Invoices.Add(newInvoice);
        db.SaveChanges();
        //Put Customer in session
        HttpContext.Session.SetInt32("CID", newCustomer.CustomerId);
        HttpContext.Session.SetInt32("InvoiceNumber", newInvoice.InvoiceId);

        return RedirectToAction("Index", "Home");
    }
    [HttpPost("/customers/select")]
    public IActionResult Select(SelectCustomer selectCustomer)
    {
        //Check if model state is valid
        if(!ModelState.IsValid){
            return Index();
        }
        // Clear Any Previous customers when switching to a new one, no logout
        HttpContext.Session.Clear();
        //Check if user exist in db
        Customer? dbCustomer = db.Customers.Include(c => c.CustomerInvoices).FirstOrDefault(c => c.Phone == selectCustomer.SelectPhone);
        if(dbCustomer == null){
            ModelState.AddModelError("SelectPhone", "not found");
            return Index();
        }
        //put Customer in session
        HttpContext.Session.SetInt32("CID", dbCustomer.CustomerId);

        return RedirectToAction("Index", "Home");
    }
}

Controllers/StockController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TireWay.Models;

namespace TireWay.Controllers;

public class StockController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private MyContext db;

    public StockController(ILogger<HomeController> logger, MyContext context)
    {
        _logger = logger;
        db = context;
    }

    [HttpGet("/stock")]
    public IActionResult Index()
    {
        return View("Index");
    }
    [HttpPost("/stock/new")]
    public IActionResult New(Tire newTire)
    {
        if(!ModelState.IsValid){
            return Index();
        }
        if(db.Tires.Any(t => t.Name == newTire.Name))
        {
            ModelState.AddModelError("Name", "already exist");
        }
        Stock? stock = db.Stock.Include(s => s.StockedTires).FirstOrDefault();
        
        if(stock != null){
            db.Tires.Add(newTire);
            stock.StockedTires.Add(newTire);
            db.SaveChanges();
        }
        return RedirectToAction("Index", "Home");
    }
    

    // [HttpPost("/stock/update")]
    // public IActionResult Update(StockHasTires updatedTire)
    // {
    //     if(!ModelState.IsValid){
    //         return Index();
    //     }
    //     Stock? stock = db.Stock.FirstOrDefault();
    //     Tire? tire = db.Tires.FirstOrDefault(t => t.TireId == updatedTire.TireId);
    //     if(stock != null && tire != null){
    //         stock.StockedTires.Add();
    //         db.SaveChanges();
    //     }
        
    //     // List<Stock> TiresInStock = db.Stock.Include(s => s.StockedTires)
    //     // .ToList();
    //     return RedirectToAction("Index", "Home");
    // }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/TiresController.cs
using Microsoft.AspNetCore.Mvc;
using TireWay.Models;
using Microsoft.EntityFrameworkCore;

namespace TireWay.Controllers;

public class TiresController : Controller
{
    private MyContext db;
    public TiresController(MyContext context)
    {
        db = context;
    }
    [HttpGet("/tires")]
    public IActionResult Index()
    {
        Stock? currentStock = db.Stock.Include(s => s.StockedTires).FirstOrDefault();
        return View("Index", currentStock);
    }
    [HttpPost("/invoices/add")]
    public IActionResult AddTire(Tire selectedTire)
    {
        if(!ModelState.IsValid){
            return Index();
        }
        Stock? stock = db.Stock.Include(s => s.StockedTires).FirstOrDefault();
        Invoice? invoice = db.Invoices.Include(i => i.InvoiceTires).FirstOrDefault(i => i.InvoiceId == HttpContext.Session.GetInt32("InvoiceNumber"));
        //check if stock has enough tires
        if(invoice != null && stock != null){
            Tire? invoiceTire = invoice.InvoiceTires.FirstOrDefault(t => t.SKU == selectedTire.SKU);
             Tire? stockTire = stock.StockedTires.FirstOrDefault(t => t.SKU == selectedTire.SKU);
             if(selectedTire.Quantity > stockTire.Quantity)
             {
                ModelState.AddModelError("Quantity", "not enough tires in stock!");
                return Index();
             }
            //if the tire exist on the invoice, only update the quantity
            if(invoiceTire != null)

            {
                invoiceTire.Quantity += selectedTire.Quantity;
                db.SaveChanges();

            } 
            //if the tire doesn't exist on the invoice, add it
            else if(invoiceTire == null)
            {
                invoice.InvoiceTires.Add(selectedTire);
                invoice.Total += (selectedTire.Quantity * selectedTire.ListPrice) * 1.08;
                db.SaveChanges();
            }
            //update the new quantity of stock now that invoice contains quantity
            stockTire.Quantity -= selectedTire.Quantity;
            db.SaveChanges();
        }
        return RedirectToAction("Index", "Home");
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]TireWay</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TireWay.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="icon" href="~/images/logo.png" type="image/gif">
</head>
<style>
    * {
    font-family: 'Quicksand', sans-serif;
    }
</style>
<body>
    <div class="sidebar">
        <nav class="navbar navbar-light mb-3">
            <div class="d-flex flex-column ms-3 me-3">
                <img class="align-self-center" src="~/images/logo.png" alt="" width="150px" height="100px"/>
                <a class="navbar-brand fst-italic" style="font-size: 3rem; font-weight: bold;" asp-area="" asp-controller="Home" asp-action="Index">TireWay</a>
                <div class="d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                        <li class="nav-tab">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-tab">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-tab">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tires" asp-action="Index">Tires</a>
                        </li>
                        <li class="nav-tab">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stock" asp-action="Index">Stock</a>
                        </li>
                    </ul>
                </div>
        </nav>
        </div>
    </div>
    <div class="banner-top">
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>